server:
  port: ${PORT:8020}

datacenter:
  url: ${DATA_CENTER_CONNECT:localhost:8190}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_CONNECT:localhost:9092}
    consumer:
      group-id: bankClient